---
# This is for testing purpose only as of now, beta version
# in final version you need to change hosts to an inventory file
# and use ssh connection instead
# Note! This is untested and should not be used for now!
# Last update 2021-01-06
# By Henrik Lowenberg
#
- hosts: localhost
  connection: local
  gather_facts: true

  pre_tasks:
    - name: collect only facts about hardware
      setup:
        gather_subset:
          - 'hardware'
    - name: get file system facts
      setup: filter=ansible_mounts

  tasks:
    - name: Satellite block
      block:
        - name: Ensure that free space on / is greater than 20%
          assert:
            that:
              - item.size_available > item.size_total|float * 0.19
            msg: ‘disk space has reached 70% threshold’
          when: item.mount == "/"
          with_items: "{{ ansible_mounts }}"

        - name: Slurp up content of cgroup file
          slurp:
            src: /var/log/puppet_configgroups.txt
          register: cgroupfile

        - name: set addon fact based on content of local file
          set_fact:
            addon: >-
              "{{ cgroupfile['content'] | b64decode |
              regex_search('^ADDON=.*', multiline=True) |
              regex_replace('ADDON=') | regex_replace('\\d{2}') }}"

        - debug:
            var: addon
            verbosity: 2

        - name: download bootstrap script
          get_url:
            url: https://sat6.example.com/pub/bootstrap.py
            dest: /tmp/bootstrap.py

        - name: make bootstrap file executable
          file:
            path: /tmp/bootstrap.py
            state: file
            mode: '0700'

        - name: run bootstrap script for base RHEL OS without addons
          shell: >-
            /tmp/bootstrap.py -l satellitehostmove -p satellitehostmove
             -s sat6.example.com --fqdn {{ ansible_hostname }}
             -o MYORG -L got -g rhel7_1m/site_customer
              -a ak-auto,ak-rhel7_1m_gss
              --skip puppet --skip katello-host-tools
          when: addon is not defined

        - name: run bootstrap script for RHEL OS with addons
          shell: >-
            /tmp/bootstrap.py -l satellitehostmove -p satellitehostmove
             -s sat6.example.com --fqdn {{ ansible_hostname }}
             -o MYORG -L got -g rhel7_1m/site_customer/{{ addon }}
             -a ak-auto,ak-rhel7_1m_gss
             --skip puppet --skip katello-host-tools
          when: addon is defined

        - name: List subscribed channels on new Satellite
          yum:
            update_cache: true
            list: repos
          register: subscribedchannels

        - debug:
            var: subscribedchannels
            verbosity: 2


    - name: Puppet block
      block:
        - name: make backup of puppet.conf
          copy:
            src: /etc/puppet/puppet.conf
            dest: /etc/puppet/puppet.conf.bak

        - name: stop puppet service
          service:
            name: puppet
            state: stopped

        - name: gather puppet cert files to delete
          find:
            paths: /var/lib/puppet/ssl
            patterns: "*"
          register: files_to_delete

        - name: remove puppet cert files
          file:
            path: "{{ item.path }}"
            state: absent
          with_items: "{{ files_to_delete.files }}"

        - name: create new puppet.conf
          copy:
            dest: /etc/puppet/puppet.conf
            owner: root
            group: root
            mode: '0644'
            backup: true
            content: |
                [main]
                logdir = /var/log/puppet
                rundir = /var/run/puppet
                ssldir = $vardir/ssl
                use_srv_records = true
                srv_domain = _puppet3masters.example.com
                syslogfacility = local6
                [agent]
                classfile = $vardir/classes.txt
                localconfig = $confdir/localconfig
                pluginsource = puppet:///plugins
                pluginfactsource = puppet:///pluginfacts
                splay = true

        - name: create puppet autosign
          copy:
            dest: /etc/puppet/csr_attributes.yaml
            owner: puppet
            group: puppet
            mode: '0600'
            content: |
              ---
              custom_attributes:
                1.2.840.113549.1.9.7: PleaseAllowMeToIntroduceMyself

        - name: run puppet with the new configuration
          shell: >-
            /bin/puppet agent -t --onetime --tags no_such_tag
             --waitforcert 30 --no-daemonize
          register: puppetagentoutput
          failed_when: puppetagentoutput.rc != 2

        - debug:
            msg: puppetagentoutput.stderr

        - name: Register file
          stat:
            path: "/var/lib/puppet/state/agent_disabled.lock"
          register: lockfile

        - name: start puppet service
          service:
            name: puppet
            state: started
            enabled: true
          when: puppetagentoutput.rc == 2 and lockfile.stat.exists == False
